# -*- coding: utf-8 -*-

# self implementation generated from reading ui file 'yt_srs.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Window(QtWidgets.QWidget):
	def __init__(self):
		super().__init__()
		self.setObjectName("self")
		self.resize(526, 423)
		self.link_box = QtWidgets.QLineEdit(self)
		self.link_box.setGeometry(QtCore.QRect(10, 26, 501, 20))
		self.link_box.setObjectName("link_box")
		self.label = QtWidgets.QLabel(self)
		self.label.setGeometry(QtCore.QRect(10, 10, 55, 13))
		self.label.setObjectName("label")
		self.label_2 = QtWidgets.QLabel(self)
		self.label_2.setGeometry(QtCore.QRect(10, 60, 71, 16))
		self.label_2.setObjectName("label_2")
		self.output_box = QtWidgets.QLineEdit(self)
		self.output_box.setGeometry(QtCore.QRect(10, 80, 471, 20))
		self.output_box.setObjectName("output_box")
		self.groupBox = QtWidgets.QGroupBox(self)
		self.groupBox.setGeometry(QtCore.QRect(10, 120, 311, 241))
		self.groupBox.setObjectName("groupBox")
		self.label_3 = QtWidgets.QLabel(self.groupBox)
		self.label_3.setGeometry(QtCore.QRect(10, 20, 60, 13))
		self.label_3.setObjectName("label_3")
		self.comboBox = QtWidgets.QComboBox(self.groupBox)
		self.comboBox.setGeometry(QtCore.QRect(10, 40, 121, 22))
		self.comboBox.setObjectName("comboBox")
		self.comboBox_2 = QtWidgets.QComboBox(self.groupBox)
		self.comboBox_2.setGeometry(QtCore.QRect(170, 40, 121, 22))
		self.comboBox_2.setObjectName("comboBox_2")
		self.label_4 = QtWidgets.QLabel(self.groupBox)
		self.label_4.setGeometry(QtCore.QRect(170, 20, 61, 16))
		self.label_4.setObjectName("label_4")
		self.comboBox_3 = QtWidgets.QComboBox(self.groupBox)
		self.comboBox_3.setGeometry(QtCore.QRect(10, 100, 121, 22))
		self.comboBox_3.setObjectName("comboBox_3")
		self.label_5 = QtWidgets.QLabel(self.groupBox)
		self.label_5.setGeometry(QtCore.QRect(10, 80, 61, 16))
		self.label_5.setObjectName("label_5")
		self.comboBox_4 = QtWidgets.QComboBox(self.groupBox)
		self.comboBox_4.setGeometry(QtCore.QRect(170, 100, 121, 22))
		self.comboBox_4.setObjectName("comboBox_4")
		self.label_6 = QtWidgets.QLabel(self.groupBox)
		self.label_6.setGeometry(QtCore.QRect(170, 80, 71, 16))
		self.label_6.setObjectName("label_6")
		self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
		self.groupBox_2.setGeometry(QtCore.QRect(0, 0, 311, 251))
		self.groupBox_2.setObjectName("groupBox_2")
		self.label_8 = QtWidgets.QLabel(self.groupBox_2)
		self.label_8.setGeometry(QtCore.QRect(10, 20, 47, 13))
		self.label_8.setObjectName("label_8")
		self.note_box = QtWidgets.QComboBox(self.groupBox_2)
		self.note_box.setGeometry(QtCore.QRect(10, 40, 121, 22))
		self.note_box.setObjectName("deck_box")
		self.text_box = QtWidgets.QComboBox(self.groupBox_2)
		self.text_box.setGeometry(QtCore.QRect(170, 40, 121, 22))
		self.text_box.setObjectName("note_box")
		self.label_9 = QtWidgets.QLabel(self.groupBox_2)
		self.label_9.setGeometry(QtCore.QRect(170, 20, 61, 16))
		self.label_9.setObjectName("label_9")
		self.audio_box = QtWidgets.QComboBox(self.groupBox_2)
		self.audio_box.setGeometry(QtCore.QRect(10, 100, 121, 22))
		self.audio_box.setObjectName("audio_box")
		self.label_10 = QtWidgets.QLabel(self.groupBox_2)
		self.label_10.setGeometry(QtCore.QRect(10, 80, 61, 16))
		self.label_10.setObjectName("label_10")
		self.pic_box = QtWidgets.QComboBox(self.groupBox_2)
		self.pic_box.setGeometry(QtCore.QRect(170, 100, 121, 22))
		self.pic_box.setObjectName("pic_box")
		self.label_11 = QtWidgets.QLabel(self.groupBox_2)
		self.label_11.setGeometry(QtCore.QRect(170, 80, 71, 16))
		self.label_11.setObjectName("label_11")

		self.label_12 = QtWidgets.QLabel(self.groupBox_2)
		self.label_12.setGeometry(QtCore.QRect(10, 140, 61, 16))
		self.label_12.setObjectName("label_12")
		self.groupBox_3 = QtWidgets.QGroupBox(self)
		self.groupBox_3.setGeometry(QtCore.QRect(330, 120, 181, 151))
		self.groupBox_3.setObjectName("groupBox_3")
		self.width_box = QtWidgets.QSpinBox(self.groupBox_3)
		self.width_box.setGeometry(QtCore.QRect(10, 50, 42, 22))
		self.width_box.setObjectName("width_box")
		self.width_box.setMaximum(2500)
		self.width_box.setValue(240)
		self.label_13 = QtWidgets.QLabel(self.groupBox_3)
		self.label_13.setGeometry(QtCore.QRect(10, 30, 71, 16))
		self.label_13.setObjectName("label_13")
		self.label_14 = QtWidgets.QLabel(self.groupBox_3)
		self.label_14.setGeometry(QtCore.QRect(60, 50, 16, 16))
		self.label_14.setObjectName("label_14")
		self.crop_bottom_box = QtWidgets.QSpinBox(self.groupBox_3)
		self.crop_bottom_box.setGeometry(QtCore.QRect(10, 110, 42, 22))
		self.crop_bottom_box.setObjectName("crop_bottom_box")
		self.label_15 = QtWidgets.QLabel(self.groupBox_3)
		self.label_15.setGeometry(QtCore.QRect(60, 110, 16, 16))
		self.label_15.setObjectName("label_15")
		self.label_16 = QtWidgets.QLabel(self.groupBox_3)
		self.label_16.setGeometry(QtCore.QRect(10, 90, 71, 16))
		self.label_16.setObjectName("label_16")
		self.height_box = QtWidgets.QSpinBox(self.groupBox_3)
		self.height_box.setGeometry(QtCore.QRect(100, 50, 42, 22))
		self.height_box.setObjectName("height_box")
		self.height_box.setMaximum(2500)
		self.height_box.setValue(160)
		self.label_17 = QtWidgets.QLabel(self.groupBox_3)
		self.label_17.setGeometry(QtCore.QRect(150, 50, 16, 16))
		self.label_17.setObjectName("label_17")
		self.label_18 = QtWidgets.QLabel(self.groupBox_3)
		self.label_18.setGeometry(QtCore.QRect(100, 30, 71, 16))
		self.label_18.setObjectName("label_18")
		self.groupBox_4 = QtWidgets.QGroupBox(self)
		self.groupBox_4.setGeometry(QtCore.QRect(330, 280, 181, 131))
		self.groupBox_4.setObjectName("groupBox_4")
		self.fallback_check = QtWidgets.QCheckBox(self.groupBox_4)
		self.fallback_check.setGeometry(QtCore.QRect(10, 30, 151, 17))
		self.fallback_check.setObjectName("fallback_check")
		self.label_19 = QtWidgets.QLabel(self.groupBox_4)
		self.label_19.setGeometry(QtCore.QRect(10, 60, 47, 21))
		self.label_19.setObjectName("label_19")
		self.subs_lang_box = QtWidgets.QComboBox(self.groupBox_4)
		self.subs_lang_box.setGeometry(QtCore.QRect(70, 60, 91, 22))
		self.subs_lang_box.setObjectName("subs_lang_box")
		self.limit_box = QtWidgets.QSpinBox(self)
		self.limit_box.setGeometry(QtCore.QRect(230, 380, 42, 22))
		self.limit_box.setObjectName("limit_box")
		self.label_20 = QtWidgets.QLabel(self)
		self.label_20.setGeometry(QtCore.QRect(150, 380, 81, 21))
		self.label_20.setObjectName("label_20")
		self.label_21 = QtWidgets.QLabel(self)
		self.label_21.setGeometry(QtCore.QRect(280, 380, 41, 21))
		self.label_21.setObjectName("label_21")
		self.generate_button = QtWidgets.QPushButton(self)
		self.generate_button.setGeometry(QtCore.QRect(20, 380, 75, 23))
		self.generate_button.setObjectName("generate_button")
		self.choose_dir_button = QtWidgets.QToolButton(self)
		self.choose_dir_button.setGeometry(QtCore.QRect(490, 80, 25, 19))
		self.choose_dir_button.setObjectName("choose_dir_button")

		self.retranslateUi()
		QtCore.QMetaObject.connectSlotsByName(self)
		

	def retranslateUi(self):
		_translate = QtCore.QCoreApplication.translate
		self.setWindowTitle(_translate("self", "YT Subs2Srs"))
		self.label.setText(_translate("self", "Video Link"))
		self.label_2.setText(_translate("self", "Output Folder"))
		self.groupBox.setTitle(_translate("self", "Export Settings"))
		self.label_3.setText(_translate("self", "Note Type"))
		self.label_4.setText(_translate("self", "Text Field"))
		self.label_5.setText(_translate("self", "Audio Field"))
		self.label_6.setText(_translate("self", "Picture Field"))
		self.groupBox_2.setTitle(_translate("self", "Export Settings"))
		self.groupBox_3.setTitle(_translate("self", "Picture Settings"))
		self.label_13.setText(_translate("self", "Width"))
		self.label_14.setText(_translate("self", "px"))
		self.label_15.setText(_translate("self", "px"))
		self.label_16.setText(_translate("self", "Crop Bottom"))
		self.label_17.setText(_translate("self", "px"))
		self.label_18.setText(_translate("self", "Height"))
		self.groupBox_4.setTitle(_translate("self", "Subtitle Settings"))
		self.fallback_check.setText(_translate("self", " Fallback to auto gen subs"))
		self.label_19.setText(_translate("self", "Language"))
		self.label_20.setText(_translate("self", "Limit (optional)"))
		self.label_21.setText(_translate("self", "0 = Off"))
		self.generate_button.setText(_translate("self", "Generate!"))
		self.choose_dir_button.setText(_translate("self", "..."))


def run():
	import sys
	app = QtWidgets.QApplication(sys.argv)
	screen = Window()
	screen.show()
	sys.exit(app.exec_())

